Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

